/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UltimaOportunidadNoVuelvasAEngordarRouteImport } from './routes/ultima-oportunidad-no-vuelvas-a-engordar'
import { Route as ProtocoloNoVuelvasAEngordarRouteImport } from './routes/protocolo-no-vuelvas-a-engordar'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as IndexRouteImport } from './routes/index'

const UltimaOportunidadNoVuelvasAEngordarRoute =
  UltimaOportunidadNoVuelvasAEngordarRouteImport.update({
    id: '/ultima-oportunidad-no-vuelvas-a-engordar',
    path: '/ultima-oportunidad-no-vuelvas-a-engordar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtocoloNoVuelvasAEngordarRoute =
  ProtocoloNoVuelvasAEngordarRouteImport.update({
    id: '/protocolo-no-vuelvas-a-engordar',
    path: '/protocolo-no-vuelvas-a-engordar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/protocolo-no-vuelvas-a-engordar': typeof ProtocoloNoVuelvasAEngordarRoute
  '/ultima-oportunidad-no-vuelvas-a-engordar': typeof UltimaOportunidadNoVuelvasAEngordarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/protocolo-no-vuelvas-a-engordar': typeof ProtocoloNoVuelvasAEngordarRoute
  '/ultima-oportunidad-no-vuelvas-a-engordar': typeof UltimaOportunidadNoVuelvasAEngordarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/protocolo-no-vuelvas-a-engordar': typeof ProtocoloNoVuelvasAEngordarRoute
  '/ultima-oportunidad-no-vuelvas-a-engordar': typeof UltimaOportunidadNoVuelvasAEngordarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obrigado'
    | '/protocolo-no-vuelvas-a-engordar'
    | '/ultima-oportunidad-no-vuelvas-a-engordar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obrigado'
    | '/protocolo-no-vuelvas-a-engordar'
    | '/ultima-oportunidad-no-vuelvas-a-engordar'
  id:
    | '__root__'
    | '/'
    | '/obrigado'
    | '/protocolo-no-vuelvas-a-engordar'
    | '/ultima-oportunidad-no-vuelvas-a-engordar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObrigadoRoute: typeof ObrigadoRoute
  ProtocoloNoVuelvasAEngordarRoute: typeof ProtocoloNoVuelvasAEngordarRoute
  UltimaOportunidadNoVuelvasAEngordarRoute: typeof UltimaOportunidadNoVuelvasAEngordarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ultima-oportunidad-no-vuelvas-a-engordar': {
      id: '/ultima-oportunidad-no-vuelvas-a-engordar'
      path: '/ultima-oportunidad-no-vuelvas-a-engordar'
      fullPath: '/ultima-oportunidad-no-vuelvas-a-engordar'
      preLoaderRoute: typeof UltimaOportunidadNoVuelvasAEngordarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo-no-vuelvas-a-engordar': {
      id: '/protocolo-no-vuelvas-a-engordar'
      path: '/protocolo-no-vuelvas-a-engordar'
      fullPath: '/protocolo-no-vuelvas-a-engordar'
      preLoaderRoute: typeof ProtocoloNoVuelvasAEngordarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObrigadoRoute: ObrigadoRoute,
  ProtocoloNoVuelvasAEngordarRoute: ProtocoloNoVuelvasAEngordarRoute,
  UltimaOportunidadNoVuelvasAEngordarRoute:
    UltimaOportunidadNoVuelvasAEngordarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
